@startuml

index -- App
App -- MyPlayer
MyPlayer -- Video
MyPlayer -- Playlist
Playlist -- NightMode
Playlist -- PlaylistHeader
Playlist -- PlaylistItems
PlaylistItems -- PlaylistItem
withLink -- PlaylistItems

Video : Video(active, autoplay, endCallback, progressCallback)
Playlist : Playlist(videos, active, nightModeCallback, nightMode)
NightMode : NightMode(nightModeCallback, nightMode)
PlaylistHeader : PlaylistHeader(active, total)
PlaylistItems : PlaylistItems(video, active, played)
PlaylistItem : PlaylistItem(video, active, played)
@enduml